name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      run: |
        docker build . -t docker-django1
    - name: Run Tests
      run: |
        python manage.py test
